# إنتاج: Express يخدم /api و dist معًا (لا تستخدم serve وحده).
FROM node:20-bookworm-slim

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

# مرّر من Dokploy كـ Build Arguments — يجب تتوفر أثناء docker build حتى تُضمَّن في dist (Vite).
ARG VITE_WEB_APP_URL=
ARG VITE_ADMIN_APP_URL=
ARG VITE_API_BASE_URL=
ARG VITE_GTAG_CONVERSION_REGISTRATION=
ARG VITE_GTAG_CONVERSION_VALUE=
ARG VITE_GTAG_CONVERSION_CURRENCY=
ENV VITE_WEB_APP_URL=$VITE_WEB_APP_URL \
    VITE_ADMIN_APP_URL=$VITE_ADMIN_APP_URL \
    VITE_API_BASE_URL=$VITE_API_BASE_URL \
    VITE_GTAG_CONVERSION_REGISTRATION=$VITE_GTAG_CONVERSION_REGISTRATION \
    VITE_GTAG_CONVERSION_VALUE=$VITE_GTAG_CONVERSION_VALUE \
    VITE_GTAG_CONVERSION_CURRENCY=$VITE_GTAG_CONVERSION_CURRENCY

RUN npm run build

ENV NODE_ENV=production

EXPOSE 3000

CMD ["npm", "start"]
